name: Multiarch build
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  IMAGE: container1
  TAG: v2

jobs:
  build:
    name: Build multi-architecture image using matrix strategy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v2

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: export architecture name (removing os prefix)
        run: |
          echo "ARCH=${PLATFORM#*/}" >>${GITHUB_ENV}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE }}
          tags: ${{ env.TAG }}-${{ env.ARCH }}
          platform: ${{ matrix.platform }}
          containerfiles: Containerfile1 

      - name: Create TAR 
        run: |
          buildah push ${{ steps.build-image.image-with-tag }} oci-archive:/tmp/images/${{ steps.build-image.image-with-tag }}.tar

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name:  ${{ env.IMAGE }}-${{ env.TAG }}-${{ env.ARCH }}
          path: /tmp/images/${{ steps.build-image.image-with-tag }}.tar
          if-no-files-found: error
          retention-days: 1

  upload:
    name: Upload Multi Arch Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download images
        uses: actions/download-artifact@v3
        # All artifacts

      - name: Manifest
        run: |
          buildah manifest rm ${{ env.IMAGE }}:${{ env.TAG }}
          buildah manifest create ${{ env.IMAGE }}:${{ env.TAG }}
          for arch in "amd64" "arm64"; do
            buildah manifest add ${{ env.IMAGE }}:${{ env.TAG }}-$arch
          done 

      - name: Push To Registry
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}
          tags: ${{ env.TAG }}
          registry: quay.io/naveenrajm
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}